// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function BuildImage(arg1:context.Context,arg2:Record<string, any>):Promise<Record<string, any>>;

export function CheckDocker(arg1:context.Context):Promise<Record<string, any>>;

export function CreatePipeline(arg1:context.Context,arg2:Record<string, any>):Promise<Record<string, any>>;

export function CreateProject(arg1:context.Context,arg2:Record<string, any>):Promise<Record<string, any>>;

export function DeletePipeline(arg1:context.Context,arg2:string):Promise<boolean>;

export function DeleteProject(arg1:context.Context,arg2:string):Promise<boolean>;

export function DeployContainer(arg1:context.Context,arg2:Record<string, any>):Promise<Record<string, any>>;

export function DeployWithCompose(arg1:context.Context,arg2:Record<string, any>):Promise<Record<string, any>>;

export function ExecutePipeline(arg1:context.Context,arg2:Record<string, any>):Promise<Record<string, any>>;

export function ExportPipelineToYaml(arg1:context.Context,arg2:string):Promise<string>;

export function GenerateCompose(arg1:context.Context,arg2:Record<string, any>):Promise<string>;

export function GenerateDockerfile(arg1:context.Context,arg2:string):Promise<string>;

export function GetBuildRecord(arg1:context.Context,arg2:string):Promise<Record<string, any>>;

export function GetContainerLogs(arg1:context.Context,arg2:string,arg3:number):Promise<string>;

export function GetSettings(arg1:context.Context):Promise<Record<string, string>>;

export function GetSupportedLanguages(arg1:context.Context):Promise<Array<Record<string, string>>>;

export function ImportPipelineFromYaml(arg1:context.Context,arg2:Record<string, any>):Promise<Record<string, any>>;

export function ListBuildRecords(arg1:context.Context,arg2:string):Promise<Array<Record<string, any>>>;

export function ListContainers(arg1:context.Context):Promise<Array<Record<string, any>>>;

export function ListImages(arg1:context.Context):Promise<Array<Record<string, any>>>;

export function ListPipelines(arg1:context.Context,arg2:string):Promise<Array<Record<string, any>>>;

export function ListProjects(arg1:context.Context):Promise<Array<Record<string, any>>>;

export function PushImage(arg1:context.Context,arg2:Record<string, any>):Promise<Record<string, any>>;

export function RemoveContainer(arg1:context.Context,arg2:string):Promise<boolean>;

export function RemoveImage(arg1:context.Context,arg2:string):Promise<Record<string, any>>;

export function SaveSettings(arg1:context.Context,arg2:Record<string, any>):Promise<boolean>;

export function StartContainer(arg1:context.Context,arg2:string):Promise<boolean>;

export function StopContainer(arg1:context.Context,arg2:string):Promise<boolean>;

export function UpdateProject(arg1:context.Context,arg2:Record<string, any>):Promise<Record<string, any>>;
