// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildImage(arg1:Record<string, any>):Promise<Record<string, any>>;

export function CheckDocker():Promise<Record<string, any>>;

export function CreateProject(arg1:Record<string, any>):Promise<Record<string, any>>;

export function DeleteProject(arg1:string):Promise<boolean>;

export function DeployContainer(arg1:Record<string, any>):Promise<Record<string, any>>;

export function DeployWithCompose(arg1:Record<string, any>):Promise<Record<string, any>>;

export function GenerateCompose(arg1:Record<string, any>):Promise<string>;

export function GenerateDockerfile(arg1:string):Promise<string>;

export function GetBuildRecord(arg1:string):Promise<Record<string, any>>;

export function GetContainerLogs(arg1:string, arg2:number):Promise<string>;

export function GetSettings():Promise<Record<string, string>>;

export function GetSupportedLanguages():Promise<Array<Record<string, string>>>;

export function ListBuildRecords(arg1:string):Promise<Array<Record<string, any>>>;

export function ListContainers():Promise<Array<Record<string, any>>>;

export function ListImages():Promise<Array<Record<string, any>>>;

export function ListProjects():Promise<Array<Record<string, any>>>;

export function PushImage(arg1:Record<string, any>):Promise<Record<string, any>>;

export function RemoveContainer(arg1:string):Promise<boolean>;

export function RemoveImage(arg1:string):Promise<Record<string, any>>;

export function SaveSettings(arg1:Record<string, any>):Promise<boolean>;

export function StartContainer(arg1:string):Promise<boolean>;

export function StopContainer(arg1:string):Promise<boolean>;

export function UpdateProject(arg1:Record<string, any>):Promise<Record<string, any>>;
