// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildImage(arg1, arg2) {
  return window['go']['main']['App']['BuildImage'](arg1, arg2);
}

export function CheckDocker(arg1) {
  return window['go']['main']['App']['CheckDocker'](arg1);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function DeleteProject(arg1, arg2) {
  return window['go']['main']['App']['DeleteProject'](arg1, arg2);
}

export function DeployContainer(arg1, arg2) {
  return window['go']['main']['App']['DeployContainer'](arg1, arg2);
}

export function GenerateDockerfile(arg1, arg2) {
  return window['go']['main']['App']['GenerateDockerfile'](arg1, arg2);
}

export function GetSupportedLanguages(arg1) {
  return window['go']['main']['App']['GetSupportedLanguages'](arg1);
}

export function ListContainers(arg1) {
  return window['go']['main']['App']['ListContainers'](arg1);
}

export function ListProjects(arg1) {
  return window['go']['main']['App']['ListProjects'](arg1);
}

export function RemoveContainer(arg1, arg2) {
  return window['go']['main']['App']['RemoveContainer'](arg1, arg2);
}

export function StartContainer(arg1, arg2) {
  return window['go']['main']['App']['StartContainer'](arg1, arg2);
}

export function StopContainer(arg1, arg2) {
  return window['go']['main']['App']['StopContainer'](arg1, arg2);
}
