// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function BuildImage(arg1:context.Context,arg2:Record<string, any>):Promise<Record<string, any>>;

export function CheckDocker(arg1:context.Context):Promise<Record<string, any>>;

export function CreateProject(arg1:context.Context,arg2:Record<string, any>):Promise<Record<string, any>>;

export function DeleteProject(arg1:context.Context,arg2:string):Promise<boolean>;

export function DeployContainer(arg1:context.Context,arg2:Record<string, any>):Promise<Record<string, any>>;

export function GenerateDockerfile(arg1:context.Context,arg2:string):Promise<string>;

export function GetSupportedLanguages(arg1:context.Context):Promise<Array<Record<string, string>>>;

export function ListContainers(arg1:context.Context):Promise<Array<Record<string, any>>>;

export function ListProjects(arg1:context.Context):Promise<Array<Record<string, any>>>;

export function RemoveContainer(arg1:context.Context,arg2:string):Promise<boolean>;

export function StartContainer(arg1:context.Context,arg2:string):Promise<boolean>;

export function StopContainer(arg1:context.Context,arg2:string):Promise<boolean>;
