// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildImage(arg1) {
  return window['go']['handler']['App']['BuildImage'](arg1);
}

export function CheckDocker() {
  return window['go']['handler']['App']['CheckDocker']();
}

export function CreatePipeline(arg1) {
  return window['go']['handler']['App']['CreatePipeline'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['handler']['App']['CreateProject'](arg1);
}

export function DeletePipeline(arg1) {
  return window['go']['handler']['App']['DeletePipeline'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['handler']['App']['DeleteProject'](arg1);
}

export function DeployContainer(arg1) {
  return window['go']['handler']['App']['DeployContainer'](arg1);
}

export function DeployWithCompose(arg1) {
  return window['go']['handler']['App']['DeployWithCompose'](arg1);
}

export function DetectDockerEnv(arg1) {
  return window['go']['handler']['App']['DetectDockerEnv'](arg1);
}

export function DetectGitEnv() {
  return window['go']['handler']['App']['DetectGitEnv']();
}

export function DiagnoseBuild(arg1) {
  return window['go']['handler']['App']['DiagnoseBuild'](arg1);
}

export function ExecutePipeline(arg1) {
  return window['go']['handler']['App']['ExecutePipeline'](arg1);
}

export function ExportPipelineToYaml(arg1) {
  return window['go']['handler']['App']['ExportPipelineToYaml'](arg1);
}

export function GenerateCompose(arg1) {
  return window['go']['handler']['App']['GenerateCompose'](arg1);
}

export function GenerateDockerfile(arg1) {
  return window['go']['handler']['App']['GenerateDockerfile'](arg1);
}

export function GetAIKeyStatus() {
  return window['go']['handler']['App']['GetAIKeyStatus']();
}

export function GetBuildRecord(arg1) {
  return window['go']['handler']['App']['GetBuildRecord'](arg1);
}

export function GetContainerLogs(arg1, arg2) {
  return window['go']['handler']['App']['GetContainerLogs'](arg1, arg2);
}

export function GetGiteaStatus() {
  return window['go']['handler']['App']['GetGiteaStatus']();
}

export function GetSettings() {
  return window['go']['handler']['App']['GetSettings']();
}

export function GetSupportedLanguages() {
  return window['go']['handler']['App']['GetSupportedLanguages']();
}

export function ImportGiteaRepos(arg1) {
  return window['go']['handler']['App']['ImportGiteaRepos'](arg1);
}

export function ImportPipelineFromYaml(arg1) {
  return window['go']['handler']['App']['ImportPipelineFromYaml'](arg1);
}

export function ListAllPipelines() {
  return window['go']['handler']['App']['ListAllPipelines']();
}

export function ListBuildRecords(arg1) {
  return window['go']['handler']['App']['ListBuildRecords'](arg1);
}

export function ListContainers() {
  return window['go']['handler']['App']['ListContainers']();
}

export function ListGiteaRepos() {
  return window['go']['handler']['App']['ListGiteaRepos']();
}

export function ListImages() {
  return window['go']['handler']['App']['ListImages']();
}

export function ListPipelines(arg1) {
  return window['go']['handler']['App']['ListPipelines'](arg1);
}

export function ListProjects() {
  return window['go']['handler']['App']['ListProjects']();
}

export function PullProjectRepo(arg1) {
  return window['go']['handler']['App']['PullProjectRepo'](arg1);
}

export function PushImage(arg1) {
  return window['go']['handler']['App']['PushImage'](arg1);
}

export function RemoveContainer(arg1) {
  return window['go']['handler']['App']['RemoveContainer'](arg1);
}

export function RemoveImage(arg1) {
  return window['go']['handler']['App']['RemoveImage'](arg1);
}

export function SaveAIKey(arg1) {
  return window['go']['handler']['App']['SaveAIKey'](arg1);
}

export function SaveGiteaConfig(arg1) {
  return window['go']['handler']['App']['SaveGiteaConfig'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['handler']['App']['SaveSettings'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['handler']['App']['Shutdown'](arg1);
}

export function StartContainer(arg1) {
  return window['go']['handler']['App']['StartContainer'](arg1);
}

export function Startup(arg1) {
  return window['go']['handler']['App']['Startup'](arg1);
}

export function StopContainer(arg1) {
  return window['go']['handler']['App']['StopContainer'](arg1);
}

export function UpdatePipeline(arg1) {
  return window['go']['handler']['App']['UpdatePipeline'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['handler']['App']['UpdateProject'](arg1);
}

export function VerifyGitea() {
  return window['go']['handler']['App']['VerifyGitea']();
}
