// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handler} from '../models';
import {docker} from '../models';
import {store} from '../models';
import {git} from '../models';
import {pipeline} from '../models';
import {gitprovider} from '../models';
import {context} from '../models';

export function BuildImage(arg1:handler.BuildImageRequest):Promise<docker.BuildResult>;

export function CheckDocker():Promise<docker.Status>;

export function CreatePipeline(arg1:handler.CreatePipelineRequest):Promise<store.Pipeline>;

export function CreateProject(arg1:handler.CreateProjectRequest):Promise<store.Project>;

export function DeletePipeline(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeployContainer(arg1:handler.DeployContainerRequest):Promise<docker.DeployResult>;

export function DeployWithCompose(arg1:handler.DeployWithComposeRequest):Promise<docker.ComposeDeployResult>;

export function DetectDockerEnv(arg1:handler.DetectDockerEnvRequest):Promise<docker.EnvReport>;

export function DetectGitEnv():Promise<git.EnvReport>;

export function DiagnoseBuild(arg1:handler.DiagnoseBuildRequest):Promise<handler.DiagnoseBuildResponse>;

export function ExecutePipeline(arg1:handler.ExecutePipelineRequest):Promise<pipeline.ExecuteResult>;

export function ExportPipelineToYaml(arg1:string):Promise<string>;

export function GenerateCompose(arg1:handler.GenerateComposeRequest):Promise<string>;

export function GenerateDockerfile(arg1:string):Promise<string>;

export function GetAIKeyStatus():Promise<handler.AIKeyStatus>;

export function GetBuildRecord(arg1:string):Promise<store.BuildRecord>;

export function GetContainerLogs(arg1:string,arg2:number):Promise<string>;

export function GetDashboardStats():Promise<handler.DashboardStats>;

export function GetGiteaStatus():Promise<handler.GiteaStatusResponse>;

export function GetSettings():Promise<Record<string, string>>;

export function GetSupportedLanguages():Promise<Array<handler.Language>>;

export function ImportGiteaRepos(arg1:handler.ImportGiteaReposRequest):Promise<handler.ImportGiteaReposResponse>;

export function ImportPipelineFromYaml(arg1:handler.ImportPipelineYamlRequest):Promise<store.Pipeline>;

export function ListAllPipelines():Promise<Array<store.Pipeline>>;

export function ListBuildRecords(arg1:string):Promise<Array<store.BuildRecord>>;

export function ListContainers():Promise<Array<docker.Container>>;

export function ListGiteaRepos():Promise<Array<gitprovider.Repo>>;

export function ListImages():Promise<Array<docker.Image>>;

export function ListPipelines(arg1:string):Promise<Array<store.Pipeline>>;

export function ListProjects():Promise<Array<store.Project>>;

export function ListProjectsWithStats():Promise<Array<handler.ProjectStats>>;

export function PullProjectRepo(arg1:string):Promise<void>;

export function PushImage(arg1:handler.PushImageRequest):Promise<docker.PushResult>;

export function RemoveContainer(arg1:string):Promise<void>;

export function RemoveImage(arg1:string):Promise<void>;

export function SaveAIKey(arg1:handler.SaveAIKeyRequest):Promise<void>;

export function SaveGiteaConfig(arg1:handler.SaveGiteaConfigRequest):Promise<void>;

export function SaveSettings(arg1:handler.SaveSettingsRequest):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartContainer(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopContainer(arg1:string):Promise<void>;

export function UpdatePipeline(arg1:handler.UpdatePipelineRequest):Promise<store.Pipeline>;

export function UpdateProject(arg1:handler.UpdateProjectRequest):Promise<store.Project>;

export function VerifyGitea():Promise<gitprovider.UserInfo>;
